import Head from 'next/head'

interface HomeProps {
  content: any
}
const Home = ({}:HomeProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-transparent">
        Hello World
      </div>
    </>
  )
}
export default Home
